version: "3.8"
services:
  todo-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///todo.db
    command: ["sh", "-c", "flask db upgrade && python run.py"]
